# Generated by Django 5.2 on 2025-05-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_edges', to='routes.point')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='routes.route')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_edges', to='routes.point')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
