# Generated by Django 5.2 on 2025-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_edge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ['created_at'], 'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
    ]
