# Generated by Django 5.2 on 2025-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_edge_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('route', 'start_point', 'end_point')},
        ),
    ]
