# Generated by Django 5.2 on 2025-05-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_edge_options_alter_edge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='edge_color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
        migrations.AddField(
            model_name='route',
            name='edge_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='vertex_color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AddField(
            model_name='route',
            name='vertex_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
