# Generated by Django 5.2 on 2025-05-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_edge_color_route_edge_style_route_vertex_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='edge_style',
        ),
    ]
